[ERROR]: during executing: "openroad -exit -no_init -python /openlane/scripts/odbpy/io_place.py --config /openlane/designs/mkCla/pin_order.cfg --hor-layer met3 --ver-layer met2 --ver-width-mult 2 --hor-width-mult 2 --hor-extension 0 --ver-extension 0 --length 4 --unmatched-error --input-lef /openlane/designs/mkCla/runs/RUN_2024.02.11_06.01.39/tmp/merged.nom.lef --output-def /openlane/designs/mkCla/runs/RUN_2024.02.11_06.01.39/tmp/floorplan/4-io.def --output /openlane/designs/mkCla/runs/RUN_2024.02.11_06.01.39/tmp/floorplan/4-io.odb /openlane/designs/mkCla/runs/RUN_2024.02.11_06.01.39/tmp/floorplan/3-initial_fp.odb |& tee /dev/null /openlane/designs/mkCla/runs/RUN_2024.02.11_06.01.39/logs/floorplan/4-place_io.log"
[ERROR]: Exit code: 1
[ERROR]: Last 10 lines:
OpenROAD 6f9b2bb8b808b1bb5831d4525d868212ae50517a 
This program is licensed under the BSD-3 license. See the LICENSE file for details.
Components of this program may be licensed under more restrictive licenses which must be honored.
Top-level design name: mkCla
[WARNING]: Using min_distance 0.42 for #N pins to avoid overlap
[WARNING]: Some pins weren't matched by the config file
Those are: ['EN_val_in', 'RDY_carry', 'RDY_sum', 'RDY_val_in', 'carry', 'sum[0]', 'sum[1]', 'sum[2]', 'sum[3]', 'sum[4]', 'sum[5]', 'sum[6]', 'sum[7]', 'sum[8]', 'sum[9]', 'sum[10]', 'sum[11]', 'sum[12]', 'sum[13]', 'sum[14]', 'sum[15]', 'val_in_data_in_3', 'val_in_data_in_1[0]', 'val_in_data_in_1[1]', 'val_in_data_in_1[2]', 'val_in_data_in_1[3]', 'val_in_data_in_1[4]', 'val_in_data_in_1[5]', 'val_in_data_in_1[6]', 'val_in_data_in_1[7]', 'val_in_data_in_1[8]', 'val_in_data_in_1[9]', 'val_in_data_in_2[0]', 'val_in_data_in_2[1]', 'val_in_data_in_2[2]', 'val_in_data_in_2[3]', 'val_in_data_in_2[4]', 'val_in_data_in_2[5]', 'val_in_data_in_2[6]', 'val_in_data_in_2[7]', 'val_in_data_in_2[8]', 'val_in_data_in_2[9]', 'val_in_data_in_1[10]', 'val_in_data_in_1[11]', 'val_in_data_in_1[12]', 'val_in_data_in_1[13]', 'val_in_data_in_1[14]', 'val_in_data_in_1[15]', 'val_in_data_in_2[10]', 'val_in_data_in_2[11]', 'val_in_data_in_2[12]', 'val_in_data_in_2[13]', 'val_in_data_in_2[14]', 'val_in_data_in_2[15]']
Treating unmatched pins as errors. Exiting..
child process exited abnormally

[ERROR]: Step 4 (floorplan) failed with error:
-code 1 -level 0 -errorcode NONE -errorinfo {
    while executing
"throw_error"
    (procedure "try_exec" line 15)
    invoked from within
"try_exec $::env(OPENROAD_BIN) -exit -no_init -python {*}$args  --input-lef $::env(MERGED_LEF)  --output-def $arg_values(-output_def)  --output $arg_va..."
    (procedure "manipulate_layout" line 19)
    invoked from within
"manipulate_layout $::env(SCRIPTS_DIR)/odbpy/io_place.py -indexed_log [index_file $::env(floorplan_logs)/place_io.log] -output_def $arg_values(-output_..."
    (procedure "place_io_ol" line 50)
    invoked from within
"place_io_ol"
    (procedure "run_floorplan" line 27)
    invoked from within
"run_floorplan"} -errorline 1
[ERROR]: Flow failed.
